version: '3.6'
services:
  confluence:
    image: ragedunicorn/confluence:1.0.1-stable
    volumes:
      - confluence_data:/var/atlassian/confluence
      - confluence_logs:/opt/atlassian/confluence/logs
    depends_on:
      - postgresql
    networks:
      - confluence
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8090"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.confluence.environment: "prod"
      com.ragedunicorn.confluence.description: "Confluence"
  postgresql:
    image: ragedunicorn/postgresql:1.0.3-stable
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - confluence
    secrets:
      - com.ragedunicorn.postgresql.app_user
      - com.ragedunicorn.postgresql.app_user_password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  confluence_data: {}
  confluence_logs: {}
  postgresql_data: {}
networks:
  confluence:
    driver: overlay
secrets:
  com.ragedunicorn.postgresql.app_user:
    external: true
  com.ragedunicorn.postgresql.app_user_password:
    external: true
