version: '3.4'
services:
  confluence:
    build: .
    image: ragedunicorn/confluence:1.0.1-dev
    volumes:
      - confluence_data:/var/atlassian/confluence
      - confluence_logs:/opt/atlassian/confluence/logs
    depends_on:
      - postgresql
    networks:
      - confluence
    ports:
      - "8090:8090"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.confluence.environment: "dev"
      com.ragedunicorn.confluence.description: "Confluence"
  postgresql:
    image: ragedunicorn/postgresql:1.0.3-dev
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - confluence
    expose:
      - "5432"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.postgresql.environment: "dev"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  confluence_data: {}
  confluence_logs: {}
  postgresql_data: {}
networks:
  confluence:
    driver: bridge
