version: '3.7'
services:
  confluence:
    build: .
    image: ragedunicorn/confluence:${CONFLUENCE_TAG_VERSION}-dev
    volumes:
      - confluence_data:/var/atlassian/confluence
      - confluence_logs:/opt/atlassian/confluence/logs
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
      POSTGRESQL_DATABASE_HOSTNAME: "postgresql"
      CONFLUENCE_DATABASE_NAME: "confluence"
    depends_on:
      - postgresql
    ports:
      - "8090:8090"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.confluence.environment: "dev"
      com.ragedunicorn.confluence.description: "Confluence"
  postgresql:
    image: ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-dev
    volumes:
      - postgresql_data:/var/lib/postgresql
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
    expose:
      - "5432"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.postgresql.environment: "dev"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  confluence_data: {}
  confluence_logs: {}
  postgresql_data: {}
