version: '3.7'
services:
  confluence:
    build: .
    image: ragedunicorn/confluence:${CONFLUENCE_TAG_VERSION}-stable
    volumes:
      - confluence_data:/var/atlassian/confluence
      - confluence_logs:/opt/atlassian/confluence/logs
    depends_on:
      - postgresql
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.confluence.environment: "prod"
      com.ragedunicorn.confluence.description: "Confluence"
  postgresql:
    image: ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-stable
    volumes:
      - postgresql_data:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  confluence_data: {}
  confluence_logs: {}
  postgresql_data: {}
